apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: swiggy-app
        #image: veeranarni/hotstar:latest
        image: 113889330192.dkr.ecr.us-east-1.amazonaws.com/prajwal
        imagePullPolicy: "Always"
