apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotsta
    spec:
      containers:
      - name: hotstar-container
        image: 113889330192.dkr.ecr.us-east-1.amazonaws.com/prajwal
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hotstar-lb
spec:
  type: LoadBalancer
  selector:
    app: hotstar
  ports:
  - port: 80
    targetPort: 3000
